version: '2.0'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: delivernow
      POSTGRES_PASSWORD: 123456

  delivernow:
    image: deliver-now
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8081:8081